#
# Copyright (C) 2022 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Device Path
DEVICE_PATH := device/huawei/bond

# Inherit from hi6250-9-common
include device/huawei/hi6250-9-common/BoardConfigCommon.mk

# Display
TARGET_SCREEN_DENSITY := 420

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 25165824
BOARD_CACHEIMAGE_PARTITION_SIZE := 134217728
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_RECVENDORIMAGE_PARTITION_SIZE := 16777216

BOARD_SUPER_PARTITION_CUST_DEVICE_SIZE := 142606336
BOARD_SUPER_PARTITION_PATCH_DEVICE_SIZE := 33554432
BOARD_SUPER_PARTITION_PREAS_DEVICE_SIZE := 1182793728
BOARD_SUPER_PARTITION_PRODUCT_DEVICE_SIZE := 620756992
BOARD_SUPER_PARTITION_SYSTEM_DEVICE_SIZE := 3338665984
BOARD_SUPER_PARTITION_VENDOR_DEVICE_SIZE := 822083584

BOARD_SUPER_PARTITION_SIZE := $(shell expr $(BOARD_SUPER_PARTITION_CUST_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_ENG_SYSTEM_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_ENG_VENDOR_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_ODM_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_PATCH_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_PREAS_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_PREAVS_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_PRODUCT_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_SYSTEM_DEVICE_SIZE) + $(BOARD_SUPER_PARTITION_VENDOR_DEVICE_SIZE) )
BOARD_HUAWEI_DYNAMIC_PARTITIONS_SIZE := $(shell expr $(BOARD_SUPER_PARTITION_SIZE) - 4194304)

# Properties
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
